SELECT 
   COALESCE((regexp_split_to_array(form.doc #>> '{fields,geolocation}'::text[], ' '::text))[1], form.doc #>> '{fields,location,lat}'::text[]) AS "inputs/meta/location/lat",
   COALESCE((regexp_split_to_array(form.doc #>> '{fields,geolocation}'::text[], ' '::text))[2], form.doc #>> '{fields,location,long}'::text[]) AS "inputs/meta/location/long",
   form.doc #>> '{fields,inputs,source}'::text[] AS "inputs/source",
   form.doc #>> '{fields,inputs,source_id}'::text[] AS "inputs/source_id",
   form.doc #>> '{fields,inputs,t_lmp_date}'::text[] AS "inputs/t_lmp_date",
   COALESCE(form.doc #>> '{fields,inputs,contact,_id}'::text[], patient.doc ->> '_id'::text) AS "inputs/contact/_id",
   COALESCE(form.doc #>> '{fields,inputs,contact,name}'::text[], patient.doc ->> 'name'::text) AS "inputs/contact/name",
   COALESCE(form.doc #>> '{fields,inputs,contact,date_of_birth}'::text[], patient.doc ->> 'date_of_birth'::text) AS "inputs/contact/date_of_birth",
   COALESCE(form.doc #>> '{fields,inputs,contact,sex}'::text[], patient.doc ->> 'sex'::text) AS "inputs/contact/sex",
   form.doc #>> '{fields,inputs,contact,parent,contact,phone}'::text[] AS "inputs/contact/parent/contact/phone",
   COALESCE(form.doc #>> '{fields,patient_age_in_years}'::text[], to_char(date_part('year'::text, age(fm.reported, to_date(patient.doc ->> 'date_of_birth'::text, 'yyyy-mm-dd'::text)::timestamp without time zone)), '999'::text)) AS patient_age_in_years,
   COALESCE(form.doc #>> '{fields,patient_contact_phone}'::text[], patient.doc ->> 'phone'::text) AS patient_contact_phone,
   COALESCE(form.doc #>> '{fields,patient_id}'::text[], patient.doc ->> '_id'::text) AS patient_id,
   COALESCE(form.doc #>> '{fields,patient_name}'::text[], patient.doc ->> 'name'::text) AS patient_name,
   form.doc #>> '{fields,lmp_date}'::text[] AS lmp_date,
   form.doc #>> '{fields,edd_8601}'::text[] AS edd_8601,
   form.doc #>> '{fields,follow_up_method}'::text[] AS follow_up_method,
   form.doc #>> '{fields,delivery_plan_discussed}'::text[] AS delivery_plan_discussed,
   form.doc #>> '{fields,danger_signs}'::text[] AS danger_signs,
   form.doc #>> '{fields,referral_follow_up_needed}'::text[] AS referral_follow_up_needed,
   form.doc #>> '{fields,days_since_lmp}'::text[] AS days_since_lmp,
   form.doc #>> '{fields,weeks_since_lmp}'::text[] AS weeks_since_lmp,
   form.doc #>> '{fields,edd}'::text[] AS edd,
   form.doc #>> '{fields,trimester_1}'::text[] AS trimester_1,
   form.doc #>> '{fields,g_overview,pregnant}'::text[] AS pregnant,
   form.doc #>> '{fields,g_overview,update_edd}'::text[] AS update_edd,
   form.doc #>> '{fields,g_overview,pregnancy_status}'::text[] AS pregnancy_status,
   form.doc #>> '{fields,g_overview,edd_new}'::text[] AS edd_new,   
   form.doc #>> '{fields,g_anc_visit,anc_visit}'::text[] AS anc_visit_fac,
   form.doc #>> '{fields,g_anc_visit,anc_visit_type}'::text[] AS anc_visit_type,
   form.doc #>> '{fields,g_anc_visit,last_visit_date}'::text[] AS last_visit_date,
   form.doc #>> '{fields,g_anc_details,mother_prophylaxis}'::text[] AS mother_prophylaxis,
   form.doc #>> '{fields,g_anc_details,mother_ipt}'::text[] AS mother_ipt, 
   form.doc #>> '{fields,g_anc_details,last_dose_ipt}'::text[] AS last_dose_ipt, 
   form.doc #>> '{fields,g_tt,mother_tt}'::text[] AS mother_tt,
   form.doc #>> '{fields,g_tt,mother_tt_rcvd}'::text[] AS mother_tt_rcvd, 
   form.doc #>> '{fields,g_tt,last_dose_tt}'::text[] AS last_dose_tt,
   form.doc #>> '{fields,g_tt,hiv_test}'::text[] AS hiv_test,  
   form.doc #>> '{fields,g_tt,spouse_tested}'::text[] AS spouse_tested,  
   form.doc #>> '{fields,g_tt,mebendazole}'::text[] AS mebendazole, 
   form.doc #>> '{fields,g_nutrition,mother_muac}'::text[] AS mother_muac,
   form.doc #>> '{fields,g_nutrition,times_fed}'::text[] AS times_fed,
   form.doc #>> '{fields,g_nutrition,food_eaten}'::text[] AS food_eaten, 
   form.doc #>> '{fields,g_nutrition,mother_weight}'::text[] AS mother_weight,
   form.doc #>> '{fields,g_behavior,llin}'::text[] AS llin,
   form.doc #>> '{fields,mother_signs,g_danger_signs}'::text[] AS g_danger_signs,
   form.doc #>> '{fields,p_note}'::text[] AS p_note,
   form.doc #>> '{fields,group_followup_options,g_follow_up_method}'::text[] AS g_follow_up_method,
   form.doc #>> '{fields,group_followup_options,call_button}'::text[] AS call_button,
   form.doc #>> '{fields,group_delivery_plan,no_delivery_plan_discussed}'::text[] AS no_delivery_plan_discussed,
   form.doc #>> '{fields,group_delivery_plan,delivery_plan}'::text[] AS delivery_plan,
   form.doc #>> '{fields,group_delivery_plan,g_delivery_plan_discussed}'::text[] AS g_delivery_plan_discussed,
   form.doc #>> '{fields,group_healthy_newborn_practices,healthy_newborn_practices}'::text[] AS healthy_newborn_practices,
   form.doc #>> '{fields,group_healthy_newborn_practices,submit}'::text[] AS newborn_practices_submit,
   ''::text AS "meta/instanceID",
   form.doc ->> '_id'::text AS xmlforms_uuid,
   COALESCE(NULLIF(RIGHT(COALESCE(form.doc #>> '{fields,group_repeat,anc_visit_repeat,anc_visit_identifier}'::text[],
        form.doc #>> '{fields,g_anc_visit,anc_visit_type}'::text[]),1),''::text),'0') AS anc_visit
  FROM {{ ref("couchdb") }} form
    JOIN {{ ref("form_metadata") }} fm ON fm.uuid = (form.doc ->> '_id'::text)
    LEFT JOIN {{ ref("couchdb") }} patient ON (patient.doc ->> '_id'::text) = (form.doc #>> '{fields,patient_id}'::text[])
 WHERE (form.doc ->> 'form'::text) = 'pregnancy_visit'::text