SELECT COALESCE((regexp_split_to_array((form.doc #>> '{fields,geolocation}'::text[]), ' '::text))[1], (form.doc #>> '{fields,location,lat}'::text[])) AS "inputs/meta/location/lat",
    COALESCE((regexp_split_to_array((form.doc #>> '{fields,geolocation}'::text[]), ' '::text))[2], (form.doc #>> '{fields,location,long}'::text[])) AS "inputs/meta/location/long",
    (form.doc #>> '{fields,inputs,source}'::text[]) AS "inputs/source",
    (form.doc #>> '{fields,inputs,source_id}'::text[]) AS "inputs/source_id",
    (form.doc #>> '{fields,inputs,t_delivery_date}'::text[]) AS "inputs/t_delivery_date",
    (form.doc #>> '{fields,inputs,t_follow_up_count}'::text[]) AS "inputs/t_follow_up_count",
    COALESCE((form.doc #>> '{fields,inputs,contact,_id}'::text[]), (patient.doc ->> '_id'::text)) AS "inputs/contact/_id",
    COALESCE((form.doc #>> '{fields,inputs,contact,name}'::text[]), (patient.doc ->> 'name'::text)) AS "inputs/contact/name",
    COALESCE((form.doc #>> '{fields,inputs,contact,date_of_birth}'::text[]), (patient.doc ->> 'date_of_birth'::text)) AS "inputs/contact/date_of_birth",
    COALESCE((form.doc #>> '{fields,inputs,contact,sex}'::text[]), (patient.doc ->> 'sex'::text)) AS "inputs/contact/sex",
    (form.doc #>> '{fields,inputs,contact,parent,contact,phone}'::text[]) AS "inputs/contact/parent/contact/phone",
    COALESCE((form.doc #>> '{fields,patient_id}'::text[]), (patient.doc ->> '_id'::text)) AS patient_id,
    COALESCE((form.doc #>> '{fields,patient_name}'::text[]), (patient.doc ->> 'name'::text)) AS patient_name,
    (form.doc #>> '{fields,follow_up_method}'::text[]) AS follow_up_method,
    (form.doc #>> '{fields,follow_up_count}'::text[]) AS follow_up_count,
    (form.doc #>> '{fields,delivery_date}'::text[]) AS delivery_date,
    (form.doc #>> '{fields,baby_weight}'::text[]) AS baby_weight,
    (form.doc #>> '{fields,pregnancy_outcome}'::text[]) AS pregnancy_outcome,
    (form.doc #>> '{fields,baby_danger_signs}'::text[]) AS baby_danger_signs,
    (form.doc #>> '{fields,geolocation}'::text[]) AS geolocation,
    COALESCE((form.doc #>> '{fields,patient_age_in_years}'::text[]), to_char(date_part('year'::text, age(fm.reported, (to_date((patient.doc ->> 'date_of_birth'::text), 'yyyy-mm-dd'::text))::timestamp without time zone)), '999'::text)) AS patient_age_in_years,
    COALESCE((form.doc #>> '{fields,patient_contact_phone}'::text[]), (patient.doc ->> 'phone'::text)) AS patient_contact_phone,
    (form.doc #>> '{fields,p_note}'::text[]) AS p_note,
    (form.doc #>> '{fields,group_visit_no,g_follow_up_method}'::text[]) AS g_follow_up_method,
    (form.doc #>> '{fields,group_visit_no,call_button}'::text[]) AS call_button,
    (form.doc #>> '{fields,group_visit_no,visit_no}'::text[]) AS visit_no,
    (form.doc #>> '{fields,group_delivery_summary,g_delivery_date}'::text[]) AS g_delivery_date,
    (form.doc #>> '{fields,group_delivery_summary,g_pregnancy_outcome}'::text[]) AS g_pregnancy_outcome,
    (form.doc #>> '{fields,group_delivery_summary,display_delivery_date}'::text[]) AS display_delivery_date,
    (form.doc #>> '{fields,group_delivery_summary,display_delivery_outcome}'::text[]) AS display_pregnancy_outcome,
    (form.doc #>> '{fields,group_weight,health_facility_delivery}'::text[]) AS health_facility_delivery,
    (form.doc #>> '{fields,group_weight,g_baby_weight}'::text[]) AS g_baby_weight,
    (form.doc #>> '{fields,group_weight,display_baby_weight}'::text[]) AS display_baby_weight,
    (form.doc #>> '{fields,group_danger_signs,g_baby_danger_signs}'::text[]) AS g_baby_danger_signs,
    (form.doc #>> '{fields,group_talking_points,talking_points}'::text[]) AS talking_points,
    (form.doc #>> '{fields,group_vaccine_first_visit,vaccine_first_visit}'::text[]) AS vaccine_first_visit,
    (form.doc #>> '{fields,group_vaccine_follow_up,vaccine_follow_up_given}'::text[]) AS vaccine_follow_up_given,
    ''::text AS "meta/instanceID",
    (form.doc ->> '_id'::text) AS xmlforms_uuid
   FROM (({{ ref("couchdb") }} form
     JOIN {{ ref("form_metadata") }} fm ON ((fm.uuid = (form.doc ->> '_id'::text))))
     LEFT JOIN {{ ref("couchdb") }} patient ON (((patient.doc ->> '_id'::text) = (form.doc #>> '{fields,patient_id}'::text[]))))
  WHERE ((form.doc ->> 'form'::text) = 'postnatal_care'::text)