version: 2

models:
  - name: contactview_metadata
    columns:
      - name: uuid
        tests:
          - not_null
      - name: type
        tests:
          - not_null
          - accepted_values:
              values:
                [contact, clinic, district_hospital, health_center, person]
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('raw_contacts')
      - dbt_utils.fewer_rows_than:
          compare_model: ref('couchdb')
