name: Release
on:
  push:
    branches:
      - 148-add-automatic-releases-and-versioning

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install dependencies
        run: npm -g install @semantic-release/git @semantic-release/changelog @semantic-release/github
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
        run: npx semantic-release --dry-run
