name: Test

on: [push, pull_request]

jobs:
  dbt-unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Run dbt and tests
        run: ./run_dbt_tests.sh
        working-directory: ./tests
