name: Test

on: [push, pull_request]

jobs:
  dbt-unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Docker Hub username
        id: get-docker-hub-username
        run: echo '::set-output name=dockerhub_username::${{ secrets.DOCKERHUB_USERNAME }}'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: steps.get-docker-hub-username.outputs.dockerhub_username
      - name: Run dbt and tests
        run: ./run_dbt_tests.sh
        working-directory: ./tests
